name: "AI Code Review | AICR (LLM + Heuristics)"
description: "AI-powered Code Review (GitHub Action): Static Heuristics + optional LLM (OpenAI/Ollama) for PRs"
author: "Open-Source Contributors"
branding:
  icon: "search"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token (default uses GITHUB_TOKEN)"
    required: false
  use-llm:
    description: "Enable LLM suggestions if creds present"
    required: false
    default: "false"
  model:
    description: "LLM model name"
    required: false
  base-url:
    description: "LLM API base URL (OpenAI-compatible or Ollama)"
    required: false
  max-comments:
    description: "Maximum number of heuristic comments"
    required: false
    default: "50"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run AICR
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token || env.GITHUB_TOKEN }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_USE_LLM: ${{ inputs.use-llm }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_BASE_URL: ${{ inputs["base-url"] }}
        INPUT_MAX_COMMENTS: ${{ inputs["max-comments"] }}
      run: |
        python -m aicr.action_main
